import AllenderOQ3.Internal.NonCrossingSemantics
import AllenderOQ3.Internal.NonCrossingUnits

/-!
# Constant-free certified layers (stage 6a of the local-divisor programme)

A certified layer (`isNonCrossingMap`) is *constant-free* when its target layer
is completely filled (length exactly `w`) and every target vertex is a
computation gate (`andGate`/`orGate`) with at least one predecessor — no
literal ports, no empty predecessor sets.  `NonCrossingCF w` is the submonoid
generated by the constant-free layers; it is contained in `NonCrossing w`.

The point of constant-freeness is that such a layer *fixes the two extreme
configurations*: an `AND` over a nonempty predecessor set is false at `⊥`, an
`OR` over a nonempty predecessor set is true at `⊤`, and the filled target
layer leaves no slot stuck at `false`.  Both facts pass to the generated
submonoid, which is the input to the component and rotation lemmas of stages
6b–6c of `docs/LOCAL_DIVISOR_PLAN.md`.

Two notes on the definition.  The plan describes constant-freeness by the gate
condition alone; the width condition `entries.length = w` is added here because
without it a slot above the length of the target layer is stuck at `false` and
`⊤` is not fixed.  And this file only develops the closure properties: explicit
constant-free generators (copy layers together with their incidence
certificates) belong to the later stages, so nothing here asserts that
`NonCrossingCF w` is bigger than the trivial submonoid.

Everything here is `sorry`-free.
-/

set_option autoImplicit false
set_option linter.unusedVariables false

namespace AllenderOQ3.Internal

variable {n : Nat} (c : ADRCircuit n) (cert : IncidenceCylinder c)

/-! ## The two extreme configurations -/

/-- The all-false configuration. -/
def botConfig (w : Nat) : Config w := fun _ => false

/-- The all-true configuration. -/
def topConfig (w : Nat) : Config w := fun _ => true

/-! ## Constant-free layers -/

/-- Every vertex of the target layer is a computation gate with at least one
predecessor. -/
def ConstantFreeLayer (ell : Nat) : Prop :=
  ∀ v : LayerVertex c (ell + 1),
    (c.kind v.val).isComputation = true ∧ ∃ u, c.edge u v.val = true

/-- A width-`w` transition realised by a *constant-free* certified layer whose
target layer fills the whole width. -/
def isConstantFreeMap (w : Nat) (f : TransMonoid w) : Prop :=
  ∃ (n : Nat) (c : ADRCircuit n) (cert : IncidenceCylinder c) (ell : Nat) (x : Fin n → Bool),
    HMVNormal c ∧ TotalWidthAtMost c w ∧
      (cert.layerOrder (ell + 1)).entries.length = w ∧
      ConstantFreeLayer c ell ∧ layerTrans c cert x ell = f

/-- The submonoid generated by the constant-free layers. -/
def NonCrossingCF (w : Nat) : Submonoid (TransMonoid w) :=
  Submonoid.closure { f | isConstantFreeMap w f }

theorem isNonCrossingMap_of_isConstantFreeMap {w : Nat} {f : TransMonoid w}
    (h : isConstantFreeMap w f) : isNonCrossingMap w f := by
  obtain ⟨n', c', cert', ell', x', hN, hW, -, -, hf⟩ := h
  exact ⟨n', c', cert', ell', x', hN, hW, hf⟩

/-- Constant-free layers are certified layers, so the constant-free submonoid
sits inside `NonCrossing w`. -/
theorem nonCrossingCF_le_nonCrossing (w : Nat) : NonCrossingCF w ≤ NonCrossing w := by
  refine Submonoid.closure_le.mpr ?_
  intro f hf
  exact Submonoid.subset_closure (isNonCrossingMap_of_isConstantFreeMap hf)

/-! ## A constant-free layer fixes both extreme configurations -/

/-- Predecessors of a layer-`(ell+1)` vertex live in layer `ell`. -/
theorem layer_pred_eq (hc : WellFormedADR c) {ell : Nat} {u : Fin c.gateCount}
    {v : LayerVertex c (ell + 1)} (hu : c.edge u v.val = true) : c.layer u = ell := by
  have h := hc.1 u v.val hu
  have hv : c.layer v.val = ell + 1 := v.2
  omega

/-- A constant-free layer sends the all-false configuration to itself. -/
theorem layerTransMap_botConfig {w : Nat} (hc : WellFormedADR c) (x : Fin n → Bool) (ell : Nat)
    (hcf : ConstantFreeLayer c ell) :
    layerTransMap c cert x ell (botConfig w) = botConfig w := by
  classical
  funext j
  dsimp only [layerTransMap, botConfig]
  split
  · next h =>
    obtain ⟨hcomp, u0, hu0⟩ := hcf ((FullLayerIndexing c cert (ell + 1)).symm ⟨j.val, h⟩)
    have hlayer : c.layer u0 = ell := layer_pred_eq c hc hu0
    cases hk : c.kind ((FullLayerIndexing c cert (ell + 1)).symm ⟨j.val, h⟩).val with
    | literal i b =>
      rw [hk] at hcomp
      simp [ADRGate.isComputation] at hcomp
    | andGate =>
      simp only
      refine decide_eq_false ?_
      intro hall
      have hb := hall u0 hu0
      rw [dif_pos hlayer] at hb
      split at hb <;> simp at hb
    | orGate =>
      simp only
      refine decide_eq_false ?_
      rintro ⟨u, hu, hbody⟩
      have hlu : c.layer u = ell := layer_pred_eq c hc hu
      rw [dif_pos hlu] at hbody
      split at hbody <;> simp at hbody
  · rfl

/-- A constant-free layer with a completely filled target layer sends the
all-true configuration to itself. -/
theorem layerTransMap_topConfig {w : Nat} (hc : WellFormedADR c) (hW : TotalWidthAtMost c w)
    (x : Fin n → Bool) (ell : Nat) (hfull : (cert.layerOrder (ell + 1)).entries.length = w)
    (hcf : ConstantFreeLayer c ell) :
    layerTransMap c cert x ell (topConfig w) = topConfig w := by
  classical
  funext j
  dsimp only [layerTransMap, topConfig]
  have hj : j.val < (cert.layerOrder (ell + 1)).entries.length := by
    rw [hfull]; exact j.isLt
  rw [dif_pos hj]
  obtain ⟨hcomp, u0, hu0⟩ := hcf ((FullLayerIndexing c cert (ell + 1)).symm ⟨j.val, hj⟩)
  cases hk : c.kind ((FullLayerIndexing c cert (ell + 1)).symm ⟨j.val, hj⟩).val with
  | literal i b =>
    rw [hk] at hcomp
    simp [ADRGate.isComputation] at hcomp
  | andGate =>
    simp only
    refine decide_eq_true ?_
    intro u hu
    have hlu : c.layer u = ell := layer_pred_eq c hc hu
    rw [dif_pos hlu]
    have hlt : (FullLayerIndexing c cert ell ⟨u, hlu⟩).val < w := fullIndex_lt c cert hW ell _
    rw [dif_pos hlt]
    trivial
  | orGate =>
    simp only
    refine decide_eq_true ?_
    refine ⟨u0, hu0, ?_⟩
    have hlu : c.layer u0 = ell := layer_pred_eq c hc hu0
    rw [dif_pos hlu]
    have hlt : (FullLayerIndexing c cert ell ⟨u0, hlu⟩).val < w := fullIndex_lt c cert hW ell _
    rw [dif_pos hlt]

/-! ## Endpoint fixing passes to the generated submonoid -/

/-- The transitions fixing both extreme configurations form a submonoid. -/
def endpointSubmonoid (w : Nat) : Submonoid (TransMonoid w) where
  carrier := {g | runTrans g (botConfig w) = botConfig w ∧ runTrans g (topConfig w) = topConfig w}
  mul_mem' := by
    intro a b ha hb
    exact ⟨by rw [runTrans_mul, ha.1, hb.1], by rw [runTrans_mul, ha.2, hb.2]⟩
  one_mem' := ⟨runTrans_one _, runTrans_one _⟩

/-- **Every element of the constant-free submonoid fixes `⊥` and `⊤`.** -/
theorem endpoint_fixed_of_mem_nonCrossingCF {w : Nat} {g : TransMonoid w}
    (hg : g ∈ NonCrossingCF w) :
    runTrans g (botConfig w) = botConfig w ∧ runTrans g (topConfig w) = topConfig w := by
  have hle : NonCrossingCF w ≤ endpointSubmonoid w := by
    refine Submonoid.closure_le.mpr ?_
    rintro f ⟨n', c', cert', ell', x', hN, hW, hfull, hcf, rfl⟩
    refine ⟨?_, ?_⟩
    · exact layerTransMap_botConfig c' cert' hN.1 x' ell' hcf
    · exact layerTransMap_topConfig c' cert' hN.1 hW x' ell' hfull hcf
  exact hle hg

theorem runTrans_botConfig_of_mem_nonCrossingCF {w : Nat} {g : TransMonoid w}
    (hg : g ∈ NonCrossingCF w) : runTrans g (botConfig w) = botConfig w :=
  (endpoint_fixed_of_mem_nonCrossingCF hg).1

theorem runTrans_topConfig_of_mem_nonCrossingCF {w : Nat} {g : TransMonoid w}
    (hg : g ∈ NonCrossingCF w) : runTrans g (topConfig w) = topConfig w :=
  (endpoint_fixed_of_mem_nonCrossingCF hg).2

/-- Constant-free transitions are monotone, being non-crossing transitions. -/
theorem monotone_of_mem_nonCrossingCF {w : Nat} {g : TransMonoid w}
    (hg : g ∈ NonCrossingCF w) : Monotone (MulOpposite.unop g) :=
  monotone_of_mem_nonCrossing (nonCrossingCF_le_nonCrossing w hg)

end AllenderOQ3.Internal
