-- Cleared in iteration 8 (02_opus).
--
-- Scratch statements of the source-side and target-side fibre-contiguity facts
-- of the necklace word.  Never imported by the AllenderOQ3 roll-up; carried only
-- unproved placeholders.
--
-- The target-side statement now lives, in exactly this form, as the isolated
-- leaf `necklace_arcTarget_contiguous` in AllenderOQ3/Internal/CutNecklace.lean,
-- from which `necklace_groupedAlong_target` is fully proved.  The source-side
-- statement `KeyContiguous arcSource (necklaceWord hpl r ell)` remains one of the
-- two ingredients of the still-open `necklace_groupedAlong_source` (the other
-- being cross-layer coherence of the induced vertex orders).  Left empty.
