import AllenderOQ3.Internal.RTrivialWordACC

/-!
# The word problem of a finite `L`-trivial monoid is in `ACC`

This is the mirror image of `RTrivialWordACC`, and it is the case that matters
for the *reset* dynamics of `NonCrossing w` (the rank-one collapse discussed in
`docs/HMV_ALGEBRA_NOTES.md` §2): the submonoid generated by the constant layer
maps is `L`-trivial, not `R`-trivial, because a later constant overwrites an
earlier one.

For a word `ℓ_a … ℓ_{b-1}` the *suffix* products `q_t := ℓ_{b-t} ⋯ ℓ_{b-1}`
satisfy `q_{t+1} = ℓ_{b-t-1} * q_t`, so in an `L`-trivial monoid the left ideals
`M q_t` shrink strictly at every change and there are at most `|M|` changes.
Reading the block from the right therefore turns it into a bounded-change
coordinate, and `cascade_aperiodic_layer` recognises its final value.

Main results:

* `leftIdealCard_lt_of_ne` — strict descent of the left ideal at a change;
* `lTrivial_suffix_changes_le` — bounded change of the suffix products;
* `monoidWordACC_of_lTrivial` — the full `MonoidWordACC` interface.

Everything here is `sorry`-free.
-/

set_option autoImplicit false
set_option linter.style.longLine false

namespace AllenderOQ3
namespace Internal

attribute [local instance] Classical.propDecidable

/-! ## `L`-triviality -/

/-- **Green's relation `L` is trivial**: if `a` and `b` divide one another on
the left then they are equal. -/
def LTrivialMonoid (M : Type) [Monoid M] : Prop :=
  ∀ a b : M, (∃ u : M, u * a = b) → (∃ v : M, v * b = a) → a = b

/-- The left ideal generated by `a`, as a `Finset`. -/
noncomputable def leftIdealFinset {M : Type} [Monoid M] [Fintype M] (a : M) : Finset M :=
  Finset.univ.filter (fun c : M => ∃ u : M, u * a = c)

theorem mem_leftIdealFinset {M : Type} [Monoid M] [Fintype M] {a c : M} :
    c ∈ leftIdealFinset a ↔ ∃ u : M, u * a = c := by
  simp [leftIdealFinset]

theorem self_mem_leftIdealFinset {M : Type} [Monoid M] [Fintype M] (a : M) :
    a ∈ leftIdealFinset a :=
  mem_leftIdealFinset.mpr ⟨1, one_mul a⟩

theorem leftIdealFinset_mul_subset {M : Type} [Monoid M] [Fintype M] (a b : M) :
    leftIdealFinset (b * a) ⊆ leftIdealFinset a := by
  intro c hc
  obtain ⟨u, hu⟩ := mem_leftIdealFinset.mp hc
  exact mem_leftIdealFinset.mpr ⟨u * b, by rw [mul_assoc]; exact hu⟩

/-- The cardinality of the left ideal generated by `a`. -/
noncomputable def leftIdealCard {M : Type} [Monoid M] [Fintype M] (a : M) : Nat :=
  (leftIdealFinset a).card

theorem leftIdealCard_le_card {M : Type} [Monoid M] [Fintype M] (a : M) :
    leftIdealCard a ≤ Fintype.card M := by
  simpa [leftIdealCard, Finset.card_univ] using
    Finset.card_le_card (Finset.subset_univ (leftIdealFinset a))

theorem leftIdealCard_mul_le {M : Type} [Monoid M] [Fintype M] (a b : M) :
    leftIdealCard (b * a) ≤ leftIdealCard a :=
  Finset.card_le_card (leftIdealFinset_mul_subset a b)

/-- **Strict descent at a change.**  In an `L`-trivial monoid, multiplying on
the left by an element that actually changes `a` strictly shrinks the left ideal
of `a`. -/
theorem leftIdealCard_lt_of_ne {M : Type} [Monoid M] [Fintype M]
    (hL : LTrivialMonoid M) (a b : M) (h : b * a ≠ a) :
    leftIdealCard (b * a) < leftIdealCard a := by
  refine Finset.card_lt_card ⟨leftIdealFinset_mul_subset a b, ?_⟩
  intro hsub
  obtain ⟨v, hv⟩ := mem_leftIdealFinset.mp (hsub (self_mem_leftIdealFinset a))
  exact h (hL (b * a) a ⟨v, hv⟩ ⟨b, rfl⟩)

/-- **Bounded change of the suffix products of an `L`-trivial monoid.** -/
theorem lTrivial_suffix_changes_le {M : Type} [Monoid M] [Fintype M]
    (hL : LTrivialMonoid M) (q : Nat → M) (u : Nat → M) (len : Nat)
    (hstep : ∀ t, t < len → q (t + 1) = u t * q t) :
    ((Finset.range len).filter (fun t => q t ≠ q (t + 1))).card ≤ Fintype.card M := by
  classical
  have h1 : ∀ t, t < len → leftIdealCard (q (t + 1)) ≤ leftIdealCard (q t) := by
    intro t ht
    rw [hstep t ht]
    exact leftIdealCard_mul_le _ _
  have h2 : ∀ t, t < len → q t ≠ q (t + 1) →
      leftIdealCard (q (t + 1)) < leftIdealCard (q t) := by
    intro t ht hne
    rw [hstep t ht]
    refine leftIdealCard_lt_of_ne hL _ _ ?_
    rw [← hstep t ht]
    exact fun hc => hne hc.symm
  have hb : ((Finset.range len).filter (fun t => q t ≠ q (t + 1))).card
      + leftIdealCard (q len) ≤ leftIdealCard (q 0) :=
    changes_bound_of_potential (fun t => leftIdealCard (q t))
      (fun t => q t ≠ q (t + 1)) len h1 h2
  have h0 : leftIdealCard (q 0) ≤ Fintype.card M := leftIdealCard_le_card _
  omega

/-! ## A one-step unfolding of `blockProd` on the left -/

/-- Extending a block by one letter on the left. -/
theorem blockProd_cons_left {G : Type} [Monoid G] {n : Nat}
    (f : Nat → (Fin n → Bool) → G) (start c b : Nat) (hcb : c < b) (x : Fin n → Bool) :
    blockProd f start c b x = f (start + c) x * blockProd f start (c + 1) b x := by
  have hsingle : blockProd f start c (c + 1) x = f (start + c) x := by
    simp [blockProd]
  rw [← blockProd_concat f start x (Nat.le_succ c) hcb, hsingle]

/-! ## The main theorem -/

/-- **The word problem of a finite `L`-trivial monoid is in `ACC`.**

Read from the right, the suffix products of a block change at most `|M|` times
(`lTrivial_suffix_changes_le`), so the bounded-change gadget
`cascade_aperiodic_layer` recognises the value of the block exactly. -/
theorem monoidWordACC_of_lTrivial (M : Type) [Monoid M] [Finite M]
    (hL : LTrivialMonoid M) : MonoidWordACC M := by
  classical
  haveI : Fintype M := Fintype.ofFinite M
  refine ⟨2, 9, rTrivialExponent (Fintype.card M), le_refl 2, ?_⟩
  intro n letter size hrec start len
  set K := Fintype.card M with hK
  have key : ∀ (a b : Nat) (g : M), ∃ c : ACCCircuit n 2,
      WellFormedACC c ∧ (∀ q, c.layer q ≤ 9) ∧
      c.gateCount ≤ (size + len + 2) ^ rTrivialExponent K ∧
      (∀ x, ACCAccepts c x → blockProd letter start a b x = g) ∧
      (a ≤ b → b ≤ len → ∀ x, blockProd letter start a b x = g → ACCAccepts c x) := by
    intro a b g
    by_cases hab : a ≤ b ∧ b ≤ len
    · obtain ⟨hab1, hab2⟩ := hab
      have hrecL : ∀ (i : Fin (b - a)) (l : M), ∃ c : ACCCircuit n 2,
          WellFormedACC c ∧ (∀ q, c.layer q ≤ 2) ∧ c.gateCount ≤ size ∧
          (∀ x, ACCAccepts c x ↔ letter (start + (b - i.val - 1)) x = l) :=
        fun i l => hrec (start + (b - i.val - 1)) l
      choose recL hrecLwf hrecLlay hrecLsz hrecLacc using hrecL
      set z : Fin (b - a + 1) → (Fin n → Bool) → M :=
        fun i x => blockProd letter start (b - i.val) b x with hz
      have hstep : ∀ (t : Nat), t < b - a → ∀ x : Fin n → Bool,
          blockProd letter start (b - (t + 1)) b x
            = letter (start + (b - t - 1)) x * blockProd letter start (b - t) b x := by
        intro t ht x
        have hlt : b - t - 1 < b := by omega
        have hsucc : b - t - 1 + 1 = b - t := by omega
        have h := blockProd_cons_left letter start (b - t - 1) b hlt x
        rw [show b - (t + 1) = b - t - 1 by omega, h, hsucc]
      have hzsucc : ∀ (i : Fin (b - a)) (x : Fin n → Bool),
          z i.succ x = letter (start + (b - i.val - 1)) x * z (Fin.castSucc i) x := by
        intro i x
        simp only [hz, Fin.val_succ, Fin.val_castSucc]
        exact hstep i.val i.isLt x
      have hchanges : ∀ x : Fin n → Bool,
          (Finset.univ.filter
            (fun i : Fin (b - a) => z (Fin.castSucc i) x ≠ z i.succ x)).card ≤ K := by
        intro x
        have hcount := lTrivial_suffix_changes_le hL
          (fun t => blockProd letter start (b - t) b x)
          (fun t => letter (start + (b - t - 1)) x) (b - a)
          (fun t ht => hstep t ht x)
        have hconv : (Finset.univ.filter
            (fun i : Fin (b - a) => z (Fin.castSucc i) x ≠ z i.succ x)).card
            = ((Finset.range (b - a)).filter
              (fun t => blockProd letter start (b - t) b x
                ≠ blockProd letter start (b - (t + 1)) b x)).card := by
          simpa [hz] using
            card_filter_fin_eq_range (len := b - a)
              (fun t => blockProd letter start (b - t) b x
                ≠ blockProd letter start (b - (t + 1)) b x)
        rw [hconv]
        exact hcount
      obtain ⟨c, hcwf, hclay, hcsz, hcacc⟩ :=
        cascade_aperiodic_layer (n := n) (m := 2) (len := b - a) (K := K)
          (Z := M) (L := M) (Y := Unit) (d := 2)
          (fun i x => letter (start + (b - i.val - 1)) x)
          (fun _ _ => ())
          (fun l _ zz => l * zz)
          recL (fun _ _ => accConst n 2 true)
          hrecLwf hrecLlay hrecLsz hrecLacc
          (fun _ _ => wellFormedACC_accConst n 2 true)
          (fun _ _ q => by rw [accConst_layer]; omega)
          (fun _ _ => le_of_eq (accConst_gateCount n 2 true))
          (fun _ _ x => by simp [accAccepts_accConst])
          1 g z
          (fun x => by simp [hz])
          hzsucc hchanges
      refine ⟨c, hcwf, ?_, ?_, ?_, ?_⟩
      · intro q
        have := hclay q
        norm_num at this
        exact this
      · refine le_trans hcsz ?_
        have hcards : Fintype.card (Fin K → Fin (b - a)) = (b - a) ^ K := by
          simp
        have hcardZ : Fintype.card (Fin (K + 1) → M) = K ^ (K + 1) := by
          simp [hK]
        rw [hcards, hcardZ]
        simpa using rTrivial_size_bound (cM := K) (size := size) (len := len)
          (bl := b - a) (by omega)
      · intro x hx
        have := (hcacc x).mp hx
        simpa [hz, show b - (b - a) = a by omega] using this
      · intro _ _ x hgx
        refine (hcacc x).mpr ?_
        simpa [hz, show b - (b - a) = a by omega] using hgx
    · refine ⟨accConst n 2 false, wellFormedACC_accConst n 2 false, ?_, ?_, ?_, ?_⟩
      · intro q; rw [accConst_layer]; omega
      · rw [accConst_gateCount]
        exact Nat.one_le_pow _ _ (by omega)
      · intro x hx
        exact absurd ((accAccepts_accConst n 2 false x).mp hx) (by simp)
      · intro h1 h2
        exact absurd ⟨h1, h2⟩ hab
  choose B hBwf hBlay hBsz hBsound hBcomp using key
  exact ⟨B, hBwf, hBlay, hBsz, hBsound,
    fun x a b hab hbl => hBcomp a b _ hab hbl x rfl⟩

/-! ## Sanity witness -/

/-- An idempotent commutative monoid is `L`-trivial as well. -/
theorem lTrivialMonoid_of_idem_comm (M : Type) [CommMonoid M]
    (hidem : ∀ x : M, x * x = x) : LTrivialMonoid M := by
  intro a b hab hba
  refine rTrivialMonoid_of_idem_comm M hidem a b ?_ ?_
  · obtain ⟨u, hu⟩ := hab
    exact ⟨u, by rw [mul_comm]; exact hu⟩
  · obtain ⟨v, hv⟩ := hba
    exact ⟨v, by rw [mul_comm]; exact hv⟩

/-! ## `J`-triviality -/

/-- **Green's relation `J` is trivial**: if `a` and `b` divide one another
two-sidedly then they are equal. -/
def JTrivialMonoid (M : Type) [Monoid M] : Prop :=
  ∀ a b : M, (∃ x y : M, x * a * y = b) → (∃ x y : M, x * b * y = a) → a = b

theorem rTrivialMonoid_of_jTrivial {M : Type} [Monoid M] (hJ : JTrivialMonoid M) :
    RTrivialMonoid M := by
  rintro a b ⟨u, hu⟩ ⟨v, hv⟩
  exact hJ a b ⟨1, u, by rw [one_mul]; exact hu⟩ ⟨1, v, by rw [one_mul]; exact hv⟩

theorem lTrivialMonoid_of_jTrivial {M : Type} [Monoid M] (hJ : JTrivialMonoid M) :
    LTrivialMonoid M := by
  rintro a b ⟨u, hu⟩ ⟨v, hv⟩
  exact hJ a b ⟨u, 1, by rw [mul_one]; exact hu⟩ ⟨v, 1, by rw [mul_one]; exact hv⟩

/-- **The word problem of a finite `J`-trivial monoid is in `ACC`.** -/
theorem monoidWordACC_of_jTrivial (M : Type) [Monoid M] [Finite M]
    (hJ : JTrivialMonoid M) : MonoidWordACC M :=
  monoidWordACC_of_rTrivial M (rTrivialMonoid_of_jTrivial hJ)

end Internal
end AllenderOQ3
