import AllenderOQ3.Internal.BlockCycle
import AllenderOQ3.Internal.NecklaceCross

set_option autoImplicit false

/-!
# The source grouping obligation above the bottom layer

The layer listing of layer `m + 1` is generated by the *incoming* arcs of
transition `m` (`necklaceLayerOrder_succ`), while the grouping obligation at
transition `m + 1` concerns the *outgoing* arcs of the same layer.  The two
cyclic orders agree because they are generated by one and the same successor
map on layer-`(m+1)` vertices:

* along the necklace of transition `m` the target vertex changes exactly at the
  exit of a target fibre, and the new vertex is `arcTarget (arcPerm m e)`;
* along the necklace of transition `m + 1` the source vertex changes exactly at
  the exit of a source fibre, and by `exit_agree` the new vertex is again
  `arcTarget (arcPerm m e)` for the corresponding level-`m` exit `e`.

`blockSucc` names that successor map, and `BlockCycle` turns the agreement into
a cyclic rotation of the two block orders.
-/

namespace AllenderOQ3.Internal

variable {n : Nat} {c : ADRCircuit n}

/-! ## The block successor on a layer -/

open Classical in
/-- The successor of a layer-`(m+1)` vertex in the cyclic order generated by
the necklace of transition `m`: the target of the necklace step out of the exit
arc of its target fibre. -/
noncomputable def blockSucc (hpl : ProperLayered c) (r : OrientableRotation c)
    (m : Nat) (v : LayerVertex c (m + 1)) : LayerVertex c (m + 1) :=
  if h : ∃ e : TransitionArc c m,
      arcTarget e = v ∧ arcTarget ((arcPerm hpl r m) e) ≠ v then
    arcTarget ((arcPerm hpl r m) h.choose)
  else v

theorem blockSucc_eq (hpl : ProperLayered c)
    (hsrc : ∃! s, IsGraphSource c s) (hsnk : ∃! t, IsGraphSink c t)
    (r : OrientableRotation c) (hg : rotationGenus r = 0) {m : Nat}
    (e : TransitionArc c m)
    (hex : arcTarget ((arcPerm hpl r m) e) ≠ arcTarget e) :
    blockSucc hpl r m (arcTarget e) = arcTarget ((arcPerm hpl r m) e) := by
  classical
  have hcond : ∃ e' : TransitionArc c m,
      arcTarget e' = arcTarget e ∧
        arcTarget ((arcPerm hpl r m) e') ≠ arcTarget e := ⟨e, rfl, hex⟩
  rw [blockSucc, dif_pos hcond]
  have hspec := hcond.choose_spec
  have heq : hcond.choose = e := by
    refine arcTarget_exit_unique hpl hsrc hsnk r hg _ e hspec.1 ?_ hex
    rw [hspec.1]
    exact hspec.2
  rw [heq]

/-! ## Every outgoing arc of a layer has an incoming partner -/

/-- If transition `m` has at least one arc, every vertex of layer `m + 1` that
carries an outgoing arc also carries an incoming one. -/
theorem exists_incoming_of_outgoing (hpl : ProperLayered c)
    (hsrc : ∃! s, IsGraphSource c s) {m : Nat}
    (e0 : TransitionArc c m) (g : TransitionArc c (m + 1)) :
    ∃ e : TransitionArc c m, arcTarget e = arcSource g := by
  by_cases hs : IsGraphSource c g.1.1
  · refine ⟨e0, Subtype.ext ?_⟩
    exact source_alone_in_layer hpl hsrc hs e0.1.2 (by rw [e0.2.2.2, g.2.2.1])
  · obtain ⟨u, hu⟩ : ∃ u, c.edge u g.1.1 = true := by
      by_contra hcon
      push_neg at hcon
      exact hs (fun u => by simpa using hcon u)
    have h1 := hpl _ _ hu
    have h2 := g.2.2.1
    have hlu : c.layer u = m := by omega
    exact ⟨⟨(u, g.1.1), ⟨hu, hlu, g.2.2.1⟩⟩, Subtype.ext rfl⟩

/-- A target fibre that is not the whole necklace has an exit. -/
theorem exists_exit_at (hpl : ProperLayered c)
    (hsrc : ∃! s, IsGraphSource c s) (hsnk : ∃! t, IsGraphSink c t)
    (r : OrientableRotation c) (hg : rotationGenus r = 0) {m : Nat}
    (v : LayerVertex c (m + 1)) (e : TransitionArc c m) (hev : arcTarget e = v)
    (e' : TransitionArc c m) (he' : arcTarget e' ≠ v) :
    ∃ x : TransitionArc c m,
      arcTarget x = v ∧ arcTarget ((arcPerm hpl r m) x) ≠ v := by
  classical
  obtain ⟨k, hk⟩ := single_orbit_all hpl hsrc hsnk r hg m e' e
  have hex : ∃ j, arcTarget (((arcPerm hpl r m) ^ j) e) ≠ v := ⟨k, by rw [hk]; exact he'⟩
  have hKspec := Nat.find_spec hex
  have hKpos : 0 < Nat.find hex := by
    rcases Nat.eq_zero_or_pos (Nat.find hex) with h | h
    · exfalso
      rw [h, pow_zero] at hKspec
      exact hKspec hev
    · exact h
  refine ⟨((arcPerm hpl r m) ^ (Nat.find hex - 1)) e, ?_, ?_⟩
  · have h := Nat.find_min hex (m := Nat.find hex - 1) (by omega)
    exact not_not.mp h
  · have hstep : (arcPerm hpl r m) (((arcPerm hpl r m) ^ (Nat.find hex - 1)) e)
        = ((arcPerm hpl r m) ^ Nat.find hex) e := by
      rw [← Equiv.Perm.mul_apply, ← pow_succ']
      congr 2
      omega
    rw [hstep]
    exact hKspec

/-! ## The two necklaces move the layer by the same successor -/

theorem blockSucc_step_target (hpl : ProperLayered c)
    (hsrc : ∃! s, IsGraphSource c s) (hsnk : ∃! t, IsGraphSink c t)
    (r : OrientableRotation c) (hg : rotationGenus r = 0) {m : Nat}
    (e : TransitionArc c m) :
    arcTarget e = arcTarget ((arcPerm hpl r m) e) ∨
      blockSucc hpl r m (arcTarget e) = arcTarget ((arcPerm hpl r m) e) := by
  by_cases h : arcTarget ((arcPerm hpl r m) e) = arcTarget e
  · exact Or.inl h.symm
  · exact Or.inr (blockSucc_eq hpl hsrc hsnk r hg e h)

theorem blockSucc_step_source (hpl : ProperLayered c)
    (hsrc : ∃! s, IsGraphSource c s) (hsnk : ∃! t, IsGraphSink c t)
    (r : OrientableRotation c) (hg : rotationGenus r = 0) {m : Nat}
    (e0 : TransitionArc c m) (g : TransitionArc c (m + 1)) :
    arcSource g = arcSource ((arcPerm hpl r (m + 1)) g) ∨
      blockSucc hpl r m (arcSource g) = arcSource ((arcPerm hpl r (m + 1)) g) := by
  by_cases hEq : arcSource ((arcPerm hpl r (m + 1)) g) = arcSource g
  · exact Or.inl hEq.symm
  right
  obtain ⟨e, he⟩ := exists_incoming_of_outgoing hpl hsrc e0 g
  obtain ⟨e2, he2⟩ :=
    exists_incoming_of_outgoing hpl hsrc e0 ((arcPerm hpl r (m + 1)) g)
  have hne2 : arcTarget e2 ≠ arcSource g := by
    rw [he2]
    exact hEq
  obtain ⟨x, hx1, hx2⟩ := exists_exit_at hpl hsrc hsnk r hg (arcSource g) e he e2 hne2
  have hxex : arcTarget ((arcPerm hpl r m) x) ≠ arcTarget x := by
    rw [hx1]
    exact hx2
  have hupx : dartIsUp (r.rotation (downDart x)) = true :=
    downUp_of_arcTarget_exit hpl r x hxex
  have hexitsrc : arcSource (exitArc hpl r x hupx) = arcTarget x :=
    exitArc_source hpl r x hupx
  have hagree := exit_agree hpl hsrc hsnk r hg x hupx
  have hexitex : arcSource ((arcPerm hpl r (m + 1)) (exitArc hpl r x hupx))
      ≠ arcSource (exitArc hpl r x hupx) := by
    rw [hagree, hexitsrc]
    exact hxex
  have hgx : exitArc hpl r x hupx = g :=
    arcSource_exit_unique hpl hsrc hsnk r hg _ g (by rw [hexitsrc, hx1]) hexitex hEq
  rw [← hx1, blockSucc_eq hpl hsrc hsnk r hg x hxex, ← hagree, hgx]

/-! ## A word with a single key is grouped along any listing containing it -/

theorem groupedAlong_of_const_key {alpha beta : Type}
    (key : alpha → beta) (w : List alpha) (v : beta) (hall : ∀ a ∈ w, key a = v)
    (ls : List beta) (hnd : ls.Nodup) (hv : v ∈ ls) : GroupedAlong key ls w := by
  obtain ⟨ls1, ls2, rfl⟩ : ∃ ls1 ls2, ls = ls1 ++ v :: ls2 := by
    obtain ⟨ls1, ls2, h⟩ := List.append_of_mem hv
    exact ⟨ls1, ls2, h⟩
  have hv1 : v ∉ ls1 := by
    intro hmem
    rw [List.nodup_append] at hnd
    exact (hnd.2.2 v hmem) v List.mem_cons_self rfl
  have hv2 : v ∉ ls2 := by
    have h := (List.nodup_append.mp hnd).2.1
    exact (List.nodup_cons.mp h).1
  have hbase : GroupedAlong key [v] w := ⟨w, [], (List.append_nil w).symm, hall, by simp, rfl⟩
  have h2 : GroupedAlong key ([v] ++ ls2) w := by
    refine groupedAlong_append_unused key [v] ls2 w hbase ?_
    intro e he a ha
    rw [hall a ha]
    intro hcon
    exact hv2 (hcon ▸ he)
  have h3 : GroupedAlong key ([] ++ ls1 ++ ([v] ++ ls2)) w := by
    refine groupedAlong_insert_unused_list key w ls1 [] ([v] ++ ls2) (by simpa using h2) ?_
    intro e he a ha
    rw [hall a ha]
    intro hcon
    exact hv1 (hcon ▸ he)
  simpa using h3

/-! ## The source grouping obligation -/

/-- **Cross-layer coherence.**  The source grouping obligation above the bottom
layer.  Note that the two listings themselves need *not* be cyclic rotations of
one another -- a vertex of layer `m + 1` with no outgoing arc is padded into the
source-side listing -- so the statement is genuinely the grouping one, with the
empty fibres free to sit anywhere. -/
theorem necklace_groupedAlong_source_succ (hpl : ProperLayered c)
    (r : OrientableRotation c) (hg : rotationGenus r = 0)
    (hsrc : ∃! s, IsGraphSource c s) (hsnk : ∃! t, IsGraphSink c t)
    (m : Nat) :
    ∃ (sourceList : List (LayerVertex c (m + 1)))
      (wordS : List (TransitionArc c (m + 1))),
      CyclicRotation (necklaceLayerOrder hpl r (m + 1)).entries sourceList ∧
      CyclicRotation (necklaceWord hpl r (m + 1)) wordS ∧
      GroupedAlong arcSource sourceList wordS := by
  classical
  by_cases hconst : ∀ g g' : TransitionArc c (m + 1), arcSource g = arcSource g'
  · by_cases hemp : Nonempty (TransitionArc c (m + 1))
    · refine ⟨(necklaceLayerOrder hpl r (m + 1)).entries, necklaceWord hpl r (m + 1),
        cyclicRotation_refl _, cyclicRotation_refl _, ?_⟩
      exact groupedAlong_of_const_key arcSource _ (arcSource hemp.some)
        (fun a _ => hconst a hemp.some) _ (necklaceLayerOrder hpl r (m + 1)).nodup
        ((necklaceLayerOrder hpl r (m + 1)).complete _)
    · have hW : necklaceWord hpl r (m + 1) = [] := by
        rw [necklaceWord, dif_neg hemp]
      refine ⟨(necklaceLayerOrder hpl r (m + 1)).entries, [],
        cyclicRotation_refl _, ?_, groupedAlong_nil _ _⟩
      rw [hW]
      exact cyclicRotation_refl _
  push_neg at hconst
  obtain ⟨g1, g2, hg12⟩ := hconst
  -- there is at least one arc below
  obtain ⟨e0⟩ : Nonempty (TransitionArc c m) := by
    by_contra hcon
    rw [not_nonempty_iff] at hcon
    have hs1 : IsGraphSource c g1.1.1 := by
      intro u
      by_contra hu
      have hedge : c.edge u g1.1.1 = true := by simpa using hu
      have h1 := hpl _ _ hedge
      have h2 := g1.2.2.1
      have hlu : c.layer u = m := by omega
      exact hcon.false
        (⟨(u, g1.1.1), ⟨hedge, hlu, g1.2.2.1⟩⟩ : TransitionArc c m)
    refine hg12 (Subtype.ext ?_)
    exact (source_alone_in_layer hpl hsrc hs1 g2.1.1 (by rw [g2.2.2.1, g1.2.2.1])).symm
  have hneW : Nonempty (TransitionArc c (m + 1)) := ⟨g1⟩
  have hnem : Nonempty (TransitionArc c m) := ⟨e0⟩
  -- the necklaces are orbit words, hence cycle orders
  have hcyW : CycleOrder (fun x => (arcPerm hpl r (m + 1)) x)
      (necklaceWord hpl r (m + 1)) := by
    rw [necklaceWord, dif_pos hneW]
    exact cycleOrder_orbitList _ _
  have hcyWm : CycleOrder (fun x => (arcPerm hpl r m) x) (necklaceWord hpl r m) := by
    rw [necklaceWord, dif_pos hnem]
    exact cycleOrder_orbitList _ _
  obtain ⟨WS, ⟨pS, qS, hWS1, hWS2⟩, hcontS⟩ :=
    necklace_arcSource_cyclicContiguous hpl r hg hsrc hsnk (m + 1)
  obtain ⟨WT, ⟨pT, qT, hWT1, hWT2⟩, hcontT⟩ :=
    necklace_arcTarget_cyclicContiguous hpl r hg hsrc hsnk m
  have hcyWS : CycleOrder (fun x => (arcPerm hpl r (m + 1)) x) WS := by
    rw [hWS2]
    refine cycleOrder_rotate pS qS ?_
    rw [← hWS1]
    exact hcyW
  have hcyWT : CycleOrder (fun x => (arcPerm hpl r m) x) WT := by
    rw [hWT2]
    refine cycleOrder_rotate pT qT ?_
    rw [← hWT1]
    exact hcyWm
  have hmemWS : ∀ x : TransitionArc c (m + 1), x ∈ WS := by
    intro x
    have hxW : x ∈ necklaceWord hpl r (m + 1) :=
      necklaceWord_complete hpl r hg hsrc hsnk _ x
    rw [hWS1] at hxW
    rw [hWS2]
    exact (List.mem_append.mp hxW).elim (fun h => List.mem_append_right _ h)
      (fun h => List.mem_append_left _ h)
  have hmemWT : ∀ x : TransitionArc c m, x ∈ WT := by
    intro x
    have hxW : x ∈ necklaceWord hpl r m := necklaceWord_complete hpl r hg hsrc hsnk _ x
    rw [hWT1] at hxW
    rw [hWT2]
    exact (List.mem_append.mp hxW).elim (fun h => List.mem_append_right _ h)
      (fun h => List.mem_append_left _ h)
  -- two distinct keys on each side
  obtain ⟨e1, he1⟩ := exists_incoming_of_outgoing hpl hsrc e0 g1
  obtain ⟨e2, he2⟩ := exists_incoming_of_outgoing hpl hsrc e0 g2
  have he12 : arcTarget e1 ≠ arcTarget e2 := by
    rw [he1, he2]
    exact hg12
  -- the source side is a cycle order for `blockSucc`
  have hchainS : List.IsChain (fun a b => arcSource a = arcSource b ∨
      blockSucc hpl r m (arcSource a) = arcSource b) WS := by
    refine hcyWS.1.imp ?_
    intro a b hab
    rw [← hab]
    exact blockSucc_step_source hpl hsrc hsnk r hg e0 a
  have hkeyneS : ∀ x ∈ WS.getLast?, ∀ y ∈ WS.head?, arcSource x ≠ arcSource y :=
    keys_ne_of_contiguous arcSource WS hcontS (hmemWS g1) (hmemWS g2) hg12
  have hwrapS : ∀ x ∈ WS.getLast?, ∀ y ∈ WS.head?,
      blockSucc hpl r m (arcSource x) = arcSource y := by
    intro x hx y hy
    have hstep : (arcPerm hpl r (m + 1)) x = y := hcyWS.2 x hx y hy
    rcases blockSucc_step_source hpl hsrc hsnk r hg e0 x with h | h
    · refine absurd ?_ (hkeyneS x hx y hy)
      rw [h, hstep]
    · rw [h, hstep]
  -- the target side is a cycle order for `blockSucc`
  have hchainT : List.IsChain (fun a b => arcTarget a = arcTarget b ∨
      blockSucc hpl r m (arcTarget a) = arcTarget b) WT := by
    refine hcyWT.1.imp ?_
    intro a b hab
    rw [← hab]
    exact blockSucc_step_target hpl hsrc hsnk r hg a
  have hkeyneT : ∀ x ∈ WT.getLast?, ∀ y ∈ WT.head?, arcTarget x ≠ arcTarget y :=
    keys_ne_of_contiguous arcTarget WT hcontT (hmemWT e1) (hmemWT e2) he12
  have hwrapT : ∀ x ∈ WT.getLast?, ∀ y ∈ WT.head?,
      blockSucc hpl r m (arcTarget x) = arcTarget y := by
    intro x hx y hy
    have hstep : (arcPerm hpl r m) x = y := hcyWT.2 x hx y hy
    rcases blockSucc_step_target hpl hsrc hsnk r hg x with h | h
    · refine absurd ?_ (hkeyneT x hx y hy)
      rw [h, hstep]
    · rw [h, hstep]
  have hDS : CycleOrder (blockSucc hpl r m) ((WS.map arcSource).dedup) :=
    cycleOrder_dedup_of_contiguous arcSource (blockSucc hpl r m) WS hcontS hchainS hwrapS
  have hDT : CycleOrder (blockSucc hpl r m) ((WT.map arcTarget).dedup) :=
    cycleOrder_dedup_of_contiguous arcTarget (blockSucc hpl r m) WT hcontT hchainT hwrapT
  -- the two block orders list the same vertices
  have hmemeq : ∀ v : LayerVertex c (m + 1),
      v ∈ (WT.map arcTarget).dedup ↔ v ∈ (WS.map arcSource).dedup := by
    intro v
    rw [List.mem_dedup, List.mem_dedup, List.mem_map, List.mem_map]
    constructor
    · rintro ⟨e, -, rfl⟩
      by_cases hv : arcTarget e = arcSource g1
      · exact ⟨g1, hmemWS g1, hv.symm⟩
      · have hne1 : arcTarget e1 ≠ arcTarget e := by
          rw [he1]
          exact fun hcon => hv hcon.symm
        obtain ⟨x, hx1, hx2⟩ :=
          exists_exit_at hpl hsrc hsnk r hg (arcTarget e) e rfl e1 hne1
        have hxex : arcTarget ((arcPerm hpl r m) x) ≠ arcTarget x := by
          rw [hx1]
          exact hx2
        have hupx : dartIsUp (r.rotation (downDart x)) = true :=
          downUp_of_arcTarget_exit hpl r x hxex
        refine ⟨exitArc hpl r x hupx, hmemWS _, ?_⟩
        rw [exitArc_source hpl r x hupx, hx1]
    · rintro ⟨g, -, rfl⟩
      obtain ⟨e, he⟩ := exists_incoming_of_outgoing hpl hsrc e0 g
      exact ⟨e, hmemWT e, he⟩
  have hrot1 : CyclicRotation ((WT.map arcTarget).dedup) ((WS.map arcSource).dedup) :=
    cyclicRotation_of_cycleOrder _ _ (List.nodup_dedup _) (List.nodup_dedup _)
      hmemeq hDT hDS
  have hrot0 : CyclicRotation (((necklaceWord hpl r m).map arcTarget).dedup)
      ((WT.map arcTarget).dedup) := by
    have hc : SelfContiguous ((qT.map arcTarget) ++ (pT.map arcTarget)) := by
      rw [← List.map_append, ← hWT2]
      exact selfContiguous_map arcTarget WT hcontT
    have h := cyclicRotation_dedup_of_contiguous (qT.map arcTarget) (pT.map arcTarget) hc
    rw [← List.map_append, ← List.map_append, ← hWT1, ← hWT2] at h
    exact h
  obtain ⟨PP, QQ, hPQ1, hPQ2⟩ :
      CyclicRotation (((necklaceWord hpl r m).map arcTarget).dedup)
        ((WS.map arcSource).dedup) := cyclicRotation_trans hrot0 hrot1
  -- the layer listing is the block order followed by the unused vertices
  obtain ⟨T, hT1, hT2⟩ : ∃ T : List (LayerVertex c (m + 1)),
      (necklaceLayerOrder hpl r (m + 1)).entries
          = ((necklaceWord hpl r m).map arcTarget).dedup ++ T ∧
        ∀ t ∈ T, t ∉ ((necklaceWord hpl r m).map arcTarget).dedup := by
    rw [necklaceLayerOrder_succ]
    exact ⟨_, rfl, fun t ht => by simpa using (List.mem_filter.mp ht).2⟩
  refine ⟨QQ ++ T ++ PP, WS, ?_, ⟨pS, qS, hWS1, hWS2⟩, ?_⟩
  · refine ⟨PP, QQ ++ T, ?_, ?_⟩
    · rw [hT1, hPQ1, List.append_assoc]
    · rw [List.append_assoc]
  · have hgr : GroupedAlong arcSource ((WS.map arcSource).dedup) WS :=
      groupedAlong_dedup_of_contiguous arcSource WS.length WS le_rfl hcontS
    rw [hPQ2] at hgr
    refine groupedAlong_insert_unused_list arcSource WS T QQ PP hgr ?_
    intro t ht a ha hcon
    have hmem : arcSource a ∈ (WS.map arcSource).dedup := by
      rw [List.mem_dedup, List.mem_map]
      exact ⟨a, ha, rfl⟩
    rw [hcon, hPQ2] at hmem
    refine hT2 t ht ?_
    rw [hPQ1]
    exact (List.mem_append.mp hmem).elim (fun h => List.mem_append_right _ h)
      (fun h => List.mem_append_left _ h)

/-- **The source grouping obligation.** -/
theorem necklace_groupedAlong_source (hpl : ProperLayered c)
    (r : OrientableRotation c) (hg : rotationGenus r = 0)
    (hsrc : ∃! s, IsGraphSource c s) (hsnk : ∃! t, IsGraphSink c t)
    (ell : Nat) :
    ∃ (sourceList : List (LayerVertex c ell))
      (wordS : List (TransitionArc c ell)),
      CyclicRotation (necklaceLayerOrder hpl r ell).entries sourceList ∧
      CyclicRotation (necklaceWord hpl r ell) wordS ∧
      GroupedAlong arcSource sourceList wordS := by
  cases ell with
  | zero =>
    obtain ⟨ls, v, hls, hv, hgr⟩ :=
      groupedAlong_listingOfPrefix_of_cyclicContiguous arcSource
        (necklaceWord hpl r 0)
        (necklace_arcSource_cyclicContiguous hpl r hg hsrc hsnk 0)
    refine ⟨ls, v, ?_, hv, hgr⟩
    rw [necklaceLayerOrder_zero hpl r]
    exact hls
  | succ m => exact necklace_groupedAlong_source_succ hpl r hg hsrc hsnk m

end AllenderOQ3.Internal
