import AllenderOQ3.Internal.LTrivialWordACC
import AllenderOQ3.Internal.ConstantMaps

/-!
# The reset submonoid of `NonCrossing w` and its word problem

`docs/HMV_ALGEBRA_NOTES.md` §2 records the *rank-one collapse*: the constant
layer maps (`Holonomy.constTrans`) generate a submonoid of `NonCrossing w` on
which prefix-`R`-block schemes carry no information, because a later constant
overwrites every earlier one.  Precisely that overwriting makes the submonoid
`L`-trivial, so the mirrored bounded-change analysis of `LTrivialWordACC`
applies to it and its word problem is in `ACC`.

* `resetSubmonoid` — the submonoid generated by the constant transitions;
* `mem_resetSubmonoid_iff` — its elements are exactly `1` and the constants;
* `resetSubmonoid_le_nonCrossing` — it sits inside `NonCrossing w`;
* `monoidWordACC_resetSubmonoid` — its word problem is in `ACC`.

Everything here is `sorry`-free.
-/

set_option autoImplicit false
set_option linter.style.longLine false

namespace AllenderOQ3
namespace Internal

attribute [local instance] Classical.propDecidable

variable {w : Nat}

/-- **A constant absorbs everything on its left**: composing any transition
before a reset gives the reset. -/
@[simp] theorem mul_constTrans (m : TransMonoid w) (q : Config w) :
    m * Holonomy.constTrans q = Holonomy.constTrans q :=
  transMonoid_ext (fun x => by simp)

/-- The submonoid of the transition monoid generated by the constant
transitions: the identity together with all resets. -/
def resetSubmonoid (w : Nat) : Submonoid (TransMonoid w) :=
  Submonoid.closure {f | ∃ q : Config w, f = Holonomy.constTrans q}

theorem constTrans_mem_resetSubmonoid (q : Config w) :
    Holonomy.constTrans q ∈ resetSubmonoid w :=
  Submonoid.subset_closure ⟨q, rfl⟩

/-- **The elements of the reset submonoid are the identity and the constants.** -/
theorem mem_resetSubmonoid_iff {x : TransMonoid w} :
    x ∈ resetSubmonoid w ↔ x = 1 ∨ ∃ q : Config w, x = Holonomy.constTrans q := by
  constructor
  · intro hx
    refine Submonoid.closure_induction
      (motive := fun y _ => y = 1 ∨ ∃ q : Config w, y = Holonomy.constTrans q)
      ?_ ?_ ?_ hx
    · rintro y ⟨q, rfl⟩
      exact Or.inr ⟨q, rfl⟩
    · exact Or.inl rfl
    · rintro y z - - (rfl | ⟨q, rfl⟩) (rfl | ⟨q', rfl⟩)
      · exact Or.inl (by simp)
      · exact Or.inr ⟨q', by simp⟩
      · exact Or.inr ⟨q, by simp⟩
      · exact Or.inr ⟨q', by simp⟩
  · rintro (rfl | ⟨q, rfl⟩)
    · exact Submonoid.one_mem _
    · exact constTrans_mem_resetSubmonoid q

/-- The reset submonoid is a submonoid of the incidence-constrained monoid. -/
theorem resetSubmonoid_le_nonCrossing : resetSubmonoid w ≤ NonCrossing w := by
  refine Submonoid.closure_le.mpr ?_
  rintro f ⟨q, rfl⟩
  exact Holonomy.constTrans_mem_nonCrossing q

/-- **The reset submonoid is `L`-trivial.** -/
theorem lTrivial_resetSubmonoid (w : Nat) : LTrivialMonoid (resetSubmonoid w) := by
  rintro ⟨a, ha⟩ ⟨b, hb⟩ ⟨⟨u, hu⟩, huv⟩ ⟨⟨v, hv⟩, hvu⟩
  have huv' : u * a = b := congrArg Subtype.val huv
  have hvu' : v * b = a := congrArg Subtype.val hvu
  refine Subtype.ext ?_
  change a = b
  rcases mem_resetSubmonoid_iff.mp ha with rfl | ⟨q, rfl⟩
  · -- `a = 1`, so `b = u`
    rcases mem_resetSubmonoid_iff.mp hb with hb1 | ⟨q, hq⟩
    · exact hb1.symm
    · -- a reset `b` forces `a = v * b = b`
      rw [hq] at hvu'
      rw [mul_constTrans] at hvu'
      rw [hq, ← hvu']
  · -- `a` is a reset, so `b = u * a = a`
    rw [mul_constTrans] at huv'
    exact huv'

instance instFiniteFunctionEndConfig : Finite (Function.End (Config w)) :=
  inferInstanceAs (Finite ((Fin w → Bool) → (Fin w → Bool)))

instance instFiniteTransMonoid : Finite (TransMonoid w) :=
  Finite.of_equiv _ MulOpposite.opEquiv

/-- **The word problem of the reset submonoid is in `ACC`.**  This is the
rank-one part of the cylindrical dynamics, handled by the `L`-trivial
bounded-change analysis. -/
theorem monoidWordACC_resetSubmonoid (w : Nat) : MonoidWordACC (resetSubmonoid w) :=
  monoidWordACC_of_lTrivial _ (lTrivial_resetSubmonoid w)

end Internal
end AllenderOQ3
