import AllenderOQ3.Internal.MonoidWordACC
import AllenderOQ3.Internal.CascadeAperiodic
import AllenderOQ3.Internal.PowerBounds

/-!
# The word problem of a finite `R`-trivial monoid is in `ACC`

This is the *aperiodic* base layer of the Barrington–Thérien cascade for
`NonCrossing w` (the group layers are supplied by `CommMonoidWordACC`, which
covers the cyclic holonomy groups).

A monoid is `R`-trivial when Green's relation `R` (mutual divisibility on the
right) is the equality relation.  The point of `R`-triviality for `ACC` is the
*bounded-change* property: along the prefix products `p_t` of a word the right
ideals `p_t M` decrease, and they decrease *strictly* whenever the prefix
product changes, so a word of any length has at most `|M|` change positions.
That is precisely the hypothesis `h_changes` of the already proved gadget
`cascade_aperiodic_layer`, which guesses the change positions and the values
between them.

Main results:

* `rightIdealCard_lt_of_ne` — the strict descent of the right ideal at a change;
* `rTrivial_prefix_changes_le` — the bounded-change property of prefix products;
* `monoidWordACC_of_rTrivial` — the full `MonoidWordACC` interface, with the
  quantitative bookkeeping (depth `9`, modulus `2`, exponent
  `rTrivialExponent (Fintype.card M)`).

Everything here is `sorry`-free.
-/

set_option autoImplicit false
set_option linter.style.longLine false

namespace AllenderOQ3
namespace Internal

attribute [local instance] Classical.propDecidable

/-! ## `R`-triviality -/

/-- **Green's relation `R` is trivial**: if `a` and `b` divide one another on
the right then they are equal. -/
def RTrivialMonoid (M : Type) [Monoid M] : Prop :=
  ∀ a b : M, (∃ u : M, a * u = b) → (∃ v : M, b * v = a) → a = b

/-- The right ideal generated by `a`, as a `Finset`. -/
noncomputable def rightIdealFinset {M : Type} [Monoid M] [Fintype M] (a : M) : Finset M :=
  Finset.univ.filter (fun c : M => ∃ u : M, a * u = c)

theorem mem_rightIdealFinset {M : Type} [Monoid M] [Fintype M] {a c : M} :
    c ∈ rightIdealFinset a ↔ ∃ u : M, a * u = c := by
  simp [rightIdealFinset]

theorem self_mem_rightIdealFinset {M : Type} [Monoid M] [Fintype M] (a : M) :
    a ∈ rightIdealFinset a :=
  mem_rightIdealFinset.mpr ⟨1, mul_one a⟩

/-- The right ideal of a right multiple is contained in the right ideal. -/
theorem rightIdealFinset_mul_subset {M : Type} [Monoid M] [Fintype M] (a b : M) :
    rightIdealFinset (a * b) ⊆ rightIdealFinset a := by
  intro c hc
  obtain ⟨u, hu⟩ := mem_rightIdealFinset.mp hc
  exact mem_rightIdealFinset.mpr ⟨b * u, by rw [← mul_assoc]; exact hu⟩

/-- The cardinality of the right ideal generated by `a`. -/
noncomputable def rightIdealCard {M : Type} [Monoid M] [Fintype M] (a : M) : Nat :=
  (rightIdealFinset a).card

theorem rightIdealCard_le_card {M : Type} [Monoid M] [Fintype M] (a : M) :
    rightIdealCard a ≤ Fintype.card M := by
  simpa [rightIdealCard, Finset.card_univ] using
    Finset.card_le_card (Finset.subset_univ (rightIdealFinset a))

theorem rightIdealCard_mul_le {M : Type} [Monoid M] [Fintype M] (a b : M) :
    rightIdealCard (a * b) ≤ rightIdealCard a :=
  Finset.card_le_card (rightIdealFinset_mul_subset a b)

/-- **Strict descent at a change.**  In an `R`-trivial monoid, multiplying on
the right by an element that actually changes `a` strictly shrinks the right
ideal of `a`. -/
theorem rightIdealCard_lt_of_ne {M : Type} [Monoid M] [Fintype M]
    (hR : RTrivialMonoid M) (a b : M) (h : a * b ≠ a) :
    rightIdealCard (a * b) < rightIdealCard a := by
  refine Finset.card_lt_card ⟨rightIdealFinset_mul_subset a b, ?_⟩
  intro hsub
  obtain ⟨v, hv⟩ := mem_rightIdealFinset.mp (hsub (self_mem_rightIdealFinset a))
  exact h (hR (a * b) a ⟨v, hv⟩ ⟨b, rfl⟩)

/-! ## The bounded-change property -/

/-- A nonincreasing `Nat`-valued potential that strictly drops at every
position satisfying `P` bounds the number of such positions. -/
theorem changes_bound_of_potential (f : Nat → Nat) (P : Nat → Prop) [DecidablePred P] :
    ∀ len, (∀ i, i < len → f (i + 1) ≤ f i) → (∀ i, i < len → P i → f (i + 1) < f i) →
      ((Finset.range len).filter P).card + f len ≤ f 0 := by
  intro len
  induction len with
  | zero => simp
  | succ k ih =>
    intro h1 h2
    have ih' := ih (fun i hi => h1 i (by omega)) (fun i hi => h2 i (by omega))
    rw [Finset.range_add_one, Finset.filter_insert]
    by_cases hk : P k
    · rw [if_pos hk, Finset.card_insert_of_notMem (by simp)]
      have := h2 k (by omega) hk
      omega
    · rw [if_neg hk]
      have := h1 k (by omega)
      omega

/-- Counting over `Fin len` and over `Finset.range len` agree. -/
theorem card_filter_fin_eq_range {len : Nat} (P : Nat → Prop) [DecidablePred P] :
    (Finset.univ.filter (fun i : Fin len => P i.val)).card
      = ((Finset.range len).filter P).card := by
  classical
  rw [Finset.card_filter, Finset.card_filter]
  exact Fin.sum_univ_eq_sum_range (fun i => if P i then 1 else 0) len

/-- **Bounded change of the prefix products of an `R`-trivial monoid.**  If
`p (t+1)` is a right multiple of `p t` for every `t`, then `p` takes a new
value at most `|M|` times. -/
theorem rTrivial_prefix_changes_le {M : Type} [Monoid M] [Fintype M]
    (hR : RTrivialMonoid M) (p : Nat → M) (u : Nat → M) (len : Nat)
    (hstep : ∀ t, t < len → p (t + 1) = p t * u t) :
    ((Finset.range len).filter (fun t => p t ≠ p (t + 1))).card ≤ Fintype.card M := by
  classical
  have h1 : ∀ t, t < len → rightIdealCard (p (t + 1)) ≤ rightIdealCard (p t) := by
    intro t ht
    rw [hstep t ht]
    exact rightIdealCard_mul_le _ _
  have h2 : ∀ t, t < len → p t ≠ p (t + 1) →
      rightIdealCard (p (t + 1)) < rightIdealCard (p t) := by
    intro t ht hne
    rw [hstep t ht]
    refine rightIdealCard_lt_of_ne hR _ _ ?_
    rw [← hstep t ht]
    exact fun hc => hne hc.symm
  have hb : ((Finset.range len).filter (fun t => p t ≠ p (t + 1))).card
      + rightIdealCard (p len) ≤ rightIdealCard (p 0) :=
    changes_bound_of_potential (fun t => rightIdealCard (p t))
      (fun t => p t ≠ p (t + 1)) len h1 h2
  have h0 : rightIdealCard (p 0) ≤ Fintype.card M := rightIdealCard_le_card _
  omega

/-! ## A one-step unfolding of `blockProd` -/

/-- Extending a block by one letter on the right. -/
theorem blockProd_succ_right {G : Type} [Monoid G] {n : Nat}
    (f : Nat → (Fin n → Bool) → G) (start a t : Nat) (x : Fin n → Bool) :
    blockProd f start a (a + t + 1) x
      = blockProd f start a (a + t) x * f (start + (a + t)) x := by
  have hsingle : blockProd f start (a + t) (a + t + 1) x = f (start + (a + t)) x := by
    simp [blockProd]
  rw [← blockProd_concat f start x (Nat.le_add_right a t) (Nat.le_succ _), hsingle]

/-! ## The exponent -/

/-- The size exponent of the `R`-trivial recognisers, as a function of the
cardinality of the monoid. -/
def rTrivialExponent (cM : Nat) : Nat := cM + cM * (cM + 1) + cM + 5

/-- The quantitative size bound of the aperiodic gadget for a block of length
`bl ≤ len`, in the form required by `MonoidWordACC`. -/
theorem rTrivial_size_bound {cM size len bl : Nat} (hbl : bl ≤ len) :
    bl ^ cM * cM ^ (cM + 1) * ((bl + 2) * (cM * 1 * (size + 1 + 1) + 1) + 1) + 1
      ≤ (size + len + 2) ^ rTrivialExponent cM := by
  set S := size + len + 2 with hS
  have hS2 : 2 ≤ S := by omega
  have hbl_le : bl ≤ S ^ 1 := by rw [pow_one]; omega
  have hpow1 : bl ^ cM ≤ S ^ (1 * cM) := pow_bnd_pow hbl_le
  have hcM : cM ≤ S ^ cM := pow_bnd_const hS2 cM
  have hpow2 : cM ^ (cM + 1) ≤ S ^ (cM * (cM + 1)) := pow_bnd_pow hcM
  have hinner1 : cM * 1 * (size + 1 + 1) ≤ S ^ (cM + 1) := by
    have h1 : cM * 1 ≤ S ^ cM := by simpa using hcM
    have h2 : size + 1 + 1 ≤ S ^ 1 := by rw [pow_one]; omega
    simpa using pow_bnd_mul h1 h2
  have hinner2 : cM * 1 * (size + 1 + 1) + 1 ≤ S ^ (cM + 2) := by
    have h1 : (1 : Nat) ≤ S ^ 0 := by simp
    have := pow_bnd_add hS2 hinner1 h1
    calc cM * 1 * (size + 1 + 1) + 1 ≤ S ^ (cM + 1 + 0 + 1) := this
      _ = S ^ (cM + 2) := by ring_nf
  have hbl2 : bl + 2 ≤ S ^ 1 := by rw [pow_one]; omega
  have hfac1 : (bl + 2) * (cM * 1 * (size + 1 + 1) + 1) ≤ S ^ (1 + (cM + 2)) :=
    pow_bnd_mul hbl2 hinner2
  have hfac2 : (bl + 2) * (cM * 1 * (size + 1 + 1) + 1) + 1 ≤ S ^ (cM + 4) := by
    have h1 : (1 : Nat) ≤ S ^ 0 := by simp
    have := pow_bnd_add hS2 hfac1 h1
    calc (bl + 2) * (cM * 1 * (size + 1 + 1) + 1) + 1 ≤ S ^ (1 + (cM + 2) + 0 + 1) := this
      _ = S ^ (cM + 4) := by ring_nf
  have hprod1 : bl ^ cM * cM ^ (cM + 1) ≤ S ^ (1 * cM + cM * (cM + 1)) :=
    pow_bnd_mul hpow1 hpow2
  have hprod2 : bl ^ cM * cM ^ (cM + 1) * ((bl + 2) * (cM * 1 * (size + 1 + 1) + 1) + 1)
      ≤ S ^ (1 * cM + cM * (cM + 1) + (cM + 4)) := pow_bnd_mul hprod1 hfac2
  have h1 : (1 : Nat) ≤ S ^ 0 := by simp
  have hfinal := pow_bnd_add hS2 hprod2 h1
  refine le_trans hfinal (pow_bnd_mono hS2 ?_)
  simp only [rTrivialExponent]
  omega

/-! ## The main theorem -/

/-- **The word problem of a finite `R`-trivial monoid is in `ACC`.**

The prefix products of a block change at most `|M|` times
(`rTrivial_prefix_changes_le`), so the bounded-change gadget
`cascade_aperiodic_layer` — which guesses the change positions and the values
in between and verifies them with the given letter recognisers — recognises the
value of the block exactly.  Blocks that are not inside the window are handled
by the constantly-false circuit, which is sound and for which nothing is
required. -/
theorem monoidWordACC_of_rTrivial (M : Type) [Monoid M] [Finite M]
    (hR : RTrivialMonoid M) : MonoidWordACC M := by
  classical
  haveI : Fintype M := Fintype.ofFinite M
  refine ⟨2, 9, rTrivialExponent (Fintype.card M), le_refl 2, ?_⟩
  intro n letter size hrec start len
  set K := Fintype.card M with hK
  have key : ∀ (a b : Nat) (g : M), ∃ c : ACCCircuit n 2,
      WellFormedACC c ∧ (∀ q, c.layer q ≤ 9) ∧
      c.gateCount ≤ (size + len + 2) ^ rTrivialExponent K ∧
      (∀ x, ACCAccepts c x → blockProd letter start a b x = g) ∧
      (a ≤ b → b ≤ len → ∀ x, blockProd letter start a b x = g → ACCAccepts c x) := by
    intro a b g
    by_cases hab : a ≤ b ∧ b ≤ len
    · obtain ⟨hab1, hab2⟩ := hab
      have hrecL : ∀ (i : Fin (b - a)) (l : M), ∃ c : ACCCircuit n 2,
          WellFormedACC c ∧ (∀ q, c.layer q ≤ 2) ∧ c.gateCount ≤ size ∧
          (∀ x, ACCAccepts c x ↔ letter (start + a + i.val) x = l) :=
        fun i l => hrec (start + a + i.val) l
      choose recL hrecLwf hrecLlay hrecLsz hrecLacc using hrecL
      set z : Fin (b - a + 1) → (Fin n → Bool) → M :=
        fun i x => blockProd letter start a (a + i.val) x with hz
      have hstep : ∀ (t : Nat) (x : Fin n → Bool),
          blockProd letter start a (a + (t + 1)) x
            = blockProd letter start a (a + t) x * letter (start + a + t) x := by
        intro t x
        have h := blockProd_succ_right letter start a t x
        rw [show a + (t + 1) = a + t + 1 from rfl, h, Nat.add_assoc]
      have hzsucc : ∀ (i : Fin (b - a)) (x : Fin n → Bool),
          z i.succ x = z (Fin.castSucc i) x * letter (start + a + i.val) x := by
        intro i x
        simp only [hz, Fin.val_succ, Fin.val_castSucc]
        exact hstep i.val x
      have hchanges : ∀ x : Fin n → Bool,
          (Finset.univ.filter
            (fun i : Fin (b - a) => z (Fin.castSucc i) x ≠ z i.succ x)).card ≤ K := by
        intro x
        have hcount := rTrivial_prefix_changes_le hR
          (fun t => blockProd letter start a (a + t) x)
          (fun t => letter (start + a + t) x) (b - a) (fun t _ => hstep t x)
        have hconv : (Finset.univ.filter
            (fun i : Fin (b - a) => z (Fin.castSucc i) x ≠ z i.succ x)).card
            = ((Finset.range (b - a)).filter
              (fun t => blockProd letter start a (a + t) x
                ≠ blockProd letter start a (a + (t + 1)) x)).card := by
          simpa [hz] using
            card_filter_fin_eq_range (len := b - a)
              (fun t => blockProd letter start a (a + t) x
                ≠ blockProd letter start a (a + (t + 1)) x)
        rw [hconv]
        exact hcount
      obtain ⟨c, hcwf, hclay, hcsz, hcacc⟩ :=
        cascade_aperiodic_layer (n := n) (m := 2) (len := b - a) (K := K)
          (Z := M) (L := M) (Y := Unit) (d := 2)
          (fun i x => letter (start + a + i.val) x)
          (fun _ _ => ())
          (fun l _ zz => zz * l)
          recL (fun _ _ => accConst n 2 true)
          hrecLwf hrecLlay hrecLsz hrecLacc
          (fun _ _ => wellFormedACC_accConst n 2 true)
          (fun _ _ q => by rw [accConst_layer]; omega)
          (fun _ _ => le_of_eq (accConst_gateCount n 2 true))
          (fun _ _ x => by simp [accAccepts_accConst])
          1 g z
          (fun x => by simp [hz])
          hzsucc hchanges
      refine ⟨c, hcwf, ?_, ?_, ?_, ?_⟩
      · intro q
        have := hclay q
        norm_num at this
        exact this
      · refine le_trans hcsz ?_
        have hcards : Fintype.card (Fin K → Fin (b - a)) = (b - a) ^ K := by
          simp
        have hcardZ : Fintype.card (Fin (K + 1) → M) = K ^ (K + 1) := by
          simp [hK]
        rw [hcards, hcardZ]
        simpa using rTrivial_size_bound (cM := K) (size := size) (len := len)
          (bl := b - a) (by omega)
      · intro x hx
        have := (hcacc x).mp hx
        simpa [hz, show a + (b - a) = b by omega] using this
      · intro _ _ x hgx
        refine (hcacc x).mpr ?_
        simpa [hz, show a + (b - a) = b by omega] using hgx
    · refine ⟨accConst n 2 false, wellFormedACC_accConst n 2 false, ?_, ?_, ?_, ?_⟩
      · intro q; rw [accConst_layer]; omega
      · rw [accConst_gateCount]
        exact Nat.one_le_pow _ _ (by omega)
      · intro x hx
        exact absurd ((accAccepts_accConst n 2 false x).mp hx) (by simp)
      · intro h1 h2
        exact absurd ⟨h1, h2⟩ hab
  choose B hBwf hBlay hBsz hBsound hBcomp using key
  exact ⟨B, hBwf, hBlay, hBsz, hBsound,
    fun x a b hab hbl => hBcomp a b _ hab hbl x rfl⟩

/-! ## Sanity witnesses -/

/-- An idempotent commutative monoid (a semilattice) is `R`-trivial. -/
theorem rTrivialMonoid_of_idem_comm (M : Type) [CommMonoid M]
    (hidem : ∀ x : M, x * x = x) : RTrivialMonoid M := by
  rintro a b ⟨u, rfl⟩ ⟨v, hv⟩
  refine Eq.symm ?_
  calc a * u = (a * u * v) * u := by rw [hv]
    _ = a * (u * u) * v := by simp [mul_comm, mul_assoc, mul_left_comm]
    _ = a * u * v := by rw [hidem u]
    _ = a := hv

/-- The interface is not met by shape alone: a genuinely two-element monoid is
`R`-trivial, and its word problem is therefore covered. -/
theorem rTrivialMonoid_fin_two : RTrivialMonoid (Fin 2) :=
  rTrivialMonoid_of_idem_comm (Fin 2) (by decide)

theorem monoidWordACC_fin_two : MonoidWordACC (Fin 2) :=
  monoidWordACC_of_rTrivial (Fin 2) rTrivialMonoid_fin_two

end Internal
end AllenderOQ3
